name: Surplus CICD

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name:  Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Get new code
        uses: actions/checkout@v4
        
      - name: Sync files and db
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            mysql_dump.sql
            **/*.sql
            .github/**
